name = "koenigslieder-cloudflare"
compatibility_date = "2025-05-05"
compatibility_flags = [ "nodejs_compat" ]
main = ".open-next/worker/index.mjs"

[site]
bucket = ".open-next/static"

[vars]
NODE_VERSION = "20"


[placement]
mode = "smart"